=== konstantinosanagn/link-prediction/src/experiment_config.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/experiment_config.schema.json",
  "title": "Experiment Config",
  "description": "Configuration for an experiment",
  "type": "object",
  "properties": {
    "seed": {
      "type": "integer"
    },
    "dataset_dir_path": {
      "type": "string"
    },
    "dataset_loader": {
      "type": "string"
    },
    "use_propositions": {
      "type": "boolean"
    },
    "train": {
      "type": "number"
    },
    "validation": {
      "type": "number"
    },
    "test": {
      "type": "number"
    },
    "experiments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "num_examples": {
            "type": "integer"
          },
          "system_prompt": {
            "type": "string"
          },
          "user_prompt_format": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== konstantinosanagn/link-prediction/src/experiment_config.json
{
  "seed": 1,
  "dataset_dir_path": "/home/parklab/data/am2_emnlp2022",
  "dataset_loader": "AmazonReviewDatasetLoader",
  "use_propositions": true,
  "train": 0.7,
  "validation": 0.2,
  "test": 0.1,
  "experiments":
  [
    {
      "name": "ZeroShot",
      "num_examples": 0,
      "system_prompt": "The four types of propositions are \"fact\", \"testimony\", \"policy\", \"value\", and \"reference\". \"Fact\" is an objective proposition, meaning there are no subjective interpretations or judgements. \"Testimony\" is also an objective proposition that is experiential. \"Policy\" is a subjective proposition that insists on a specific course of action. \"Value\" is a subjective proposition that is a personal opinion or expression of feeling. \"Reference\" refers to a resource containing objective evidence. In product reviews, reference is usually a URL to another product page, image or video.",
      "user_prompt_format": "Classify the following proposition as \"fact\", \"testimony\", \"policy\", \"value\", or \"reference\": \"{}\"\nWith no other text, answer in the desired format:\n{}"
    }
  ]
}
